name: CD

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci

      - run: npx nx run-many -t build

      - run: |
          for lib in ./dist/libs/*; do
            if [ -d "$lib" ]; then
              cd "./dist/libs/$lib"
              npm publish --provenance --access public
            fi
          done
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
